# Generated by Django 5.2 on 2025-08-13 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='disclaimer',
            field=models.TextField(blank=True, help_text='Disclaimer text displayed at the top of the post (will not appear in post excerpts)', verbose_name='Disclaimer'),
        ),
    ]
