# Generated by Django 5.2 on 2025-08-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogpage_disclaimer'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Views'),
        ),
    ]
