# Generated by Django 5.2 on 2025-10-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_blogpage_views_standardpage_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='trip_date',
            field=models.DateField(blank=True, help_text='Month and year of the trip (only these will be displayed/used)', null=True, verbose_name='Trip date'),
        ),
    ]
