# Generated by Django 5.2 on 2026-04-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_blogpage_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='headersettings',
            name='show_search',
            field=models.BooleanField(default=True, verbose_name='Show search'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='trip_date',
            field=models.DateField(blank=True, help_text='Month and year of the trip', null=True, verbose_name='Trip date'),
        ),
    ]
