# Generated by Django 5.2 on 2026-04-04 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_headersettings_show_search_alter_blogpage_trip_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='next_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.blogpage', verbose_name='Next part'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='next_part_text',
            field=models.CharField(blank=True, help_text='Text displayed on the link to the next part', max_length=255, verbose_name='Next part link text'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='prev_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.blogpage', verbose_name='Previous part'),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='prev_part_text',
            field=models.CharField(blank=True, help_text='Text displayed on the link to the previous part', max_length=255, verbose_name='Previous part link text'),
        ),
    ]
