# Generated by Django 5.2 on 2026-04-14 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_blogpage_next_part_blogpage_next_part_text_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='navlink',
            name='page',
            field=models.ForeignKey(blank=True, help_text='Select a page to link to. Takes priority over the URL field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='url',
            field=models.CharField(blank=True, help_text='Used when no page is selected. Enter a full URL (e.g. https://blog.example.com) or a path starting with / for internal links.', max_length=500, verbose_name='URL'),
        ),
    ]
