# Generated by Django 5.2 on 2026-04-14 05:42

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_navlink_page_alter_navlink_label_alter_navlink_url'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS "home_pageview"',
            reverse_sql=migrations.RunSQL.noop,
        ),  # Drop the orphaned home_pageview table.
        migrations.AlterField(
            model_name='blogpage',
            name='next_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='prev_parts', to='home.blogpage', verbose_name='Next part'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='prev_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='next_parts', to='home.blogpage', verbose_name='Previous part'),
        ),
        migrations.AlterField(
            model_name='navlink',
            name='page',
            field=models.ForeignKey(blank=True,
                                    help_text='Select a page to link to. Takes priority over the URL field.', null=True,
                                    on_delete=django.db.models.deletion.SET_NULL, related_name='nav_links',
                                    to='wagtailcore.page', verbose_name='Page'),
        ),
        migrations.CreateModel(
            name='TranslationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('anthropic', 'Anthropic (Claude)'), ('openai', 'OpenAI-compatible  (ChatGPT, DeepSeek, Mistral, Ollama, …)')], default='anthropic', max_length=50, verbose_name='AI provider')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API key')),
                ('model', models.CharField(blank=True, help_text='e.g. claude-sonnet-4-6, gpt-4o, mistral-large-latest', max_length=200, verbose_name='Model')),
                ('base_url', models.CharField(blank=True, help_text='OpenAI-compatible only. Leave blank for OpenAI. Example: https://api.deepseek.com/v1', max_length=500, verbose_name='Base URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
                ('source_locale', models.ForeignKey(blank=True, help_text='The language your posts are originally written in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.locale', verbose_name='Source language')),
            ],
            options={
                'verbose_name': 'Translation settings',
            },
        ),
        migrations.CreateModel(
            name='LanguageTranslationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(help_text='Instructions for the AI: target language, writing style, formatting rules, etc.', verbose_name='Translation prompt')),
                ('default_disclaimer', models.TextField(blank=True, help_text='Auto-filled in the page disclaimer field when translating (e.g. "Translated with AI")', verbose_name='Default disclaimer')),
                ('locale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.locale', verbose_name='Language')),
                ('translation_settings', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_configs', to='home.translationsettings')),
            ],
            options={
                'verbose_name': 'Language translation config',
                'verbose_name_plural': 'Language translation configs',
                'constraints': [models.UniqueConstraint(fields=('translation_settings', 'locale'), name='unique_language_config_per_settings')],
            },
        ),
    ]
